# Numpy

NumPy es una librería de Python especializada en el cálculo numérico y el análisis de datos, especialmente para un gran volumen de datos.

Algunos Ejercicios con Numpy

In [2]:
import numpy as np

In [3]:
##crear un areglo con los pares del 0 al 20
a = np.arange(0,21,2)
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [4]:
#Crear una matriz 3x3 con valores aleatorios entre 0 y 1.
matriz3x3 = np.random.rand(3,3)
matriz3x3

array([[0.73301358, 0.52495981, 0.52534739],
       [0.1108962 , 0.68015164, 0.53476017],
       [0.60404039, 0.05203581, 0.11658322]])

In [5]:
#Dado el arreglo arr = np.array([1, 2, 3, 4, 5]), multiplicar todos los elementos por 2.
arr = np.array([1, 2, 3, 4, 5])
arre2=arr*2
arre2

array([ 2,  4,  6,  8, 10])

In [6]:
#Calcular la suma, el promedio y el producto de los elementos en el arreglo arr = np.array([10, 20, 30, 40, 50]).
arr = np.array([10, 20, 30, 40, 50])
print(f"La suma: {arr.sum()}")
print(f"El promedio: {arr.mean()}")
print(f"El producto: {arr.prod()}")

La suma: 150
El promedio: 30.0
El producto: 12000000


In [8]:
#Crear una matriz identidad de tamaño 4x4 utilizando NumPy.
matriz4x4 = np.identity(4)
matriz4x4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

@Author: Gian Mamani